package pdf

import (
	"bytes"
	"encoding/hex"
	"testing"
)

// tiffLZWStrip is a TIFF LZW strip of tiffLZWPlain, written by Pillow 12.3.0.
// TIFF LZW uses the same MSB-first codes and early change as the PDF default,
// so it is the outside oracle for the width switch at 511 codes.
const tiffLZWStrip = "8037008655507d5a1d2d369caac0d878be13381e4d8fd083fc32af3007408ac5a074042b231e0e63a7937cbe" +
	"ae5b820b2d1770e420cb242556acc448a422ff032d8c42e6f8f1f2357e92d282865024f84459808bc962facd" +
	"d46d563505a81371a55ee07321c989c0239da4362e8b0c0c9753d0f2f643281d69313390c4126a83596b33b8" +
	"54d46a1d1a1748e6d9d010464f3cd9cb3053e1a0dd342edf05f7d091e4d27e0610efb2e21d74b41c0c94a9b0" +
	"d8f4207c7b9e1ac7f711b5f011488a4fc934ab2c24c52bb38b4f16a05830d70caf0085b3f264caf151250e2c" +
	"4152b0d4a91c310eac7568c870020f814762c4c869f8eb0ab799f7a701f178d60f25c369a05a757c9731b4d2" +
	"4fc57b7d448c4b88c8a6275b740e65383fcb0893533dee651dc1f838749c8050d0729bc4991a1c1383e97a6b" +
	"8b6049a8739c4198881f89446188509206b1705c1b8308be6891c1417c2c81c550a00d8a0450d41b052730e0" +
	"6f8aa3b9746e088368865d9520402e6b1807b0f6040c2381b216992090e42d8483f184711b4589640213c101" +
	"003a06e4d0de480186e85c2f0e47a8122416c2c1a24b9d261918588dc699ba0908831064060285395e1f9f40" +
	"61bc6b02667026431962b940239c82d97c6888a5a06c6a9107f1a4000827910e5881e418be3a0ca5d0502302" +
	"c291be44144099b25f8847796e0896a6f00e3f9923c974719502c094549d016950268a04e9cc4c0d6711524d" +
	"19e1089833054461aa480221b930339125d95a798a246826569ea0e1420092856160420d87a9147a8543d122" +
	"7a9e65585e430645d102228401e98633828440f43a920640c66380e7003c610e001934689160b07e121ec619" +
	"bc159de2e8b4689cc3b0263c9942102c5c8205500a6c9061818e0519e429e033196761de56112261f45b83e0" +
	"c174618686f96c30094591001919a1c942371be4a0880a1c27994c761827a0722180c601363113a71874698c" +
	"277986298d66809e4b03e7709a5e9e60285a4b9fc621a24d88a13968511884a1b03207c5c0e25c9880f8a645" +
	"8104a8384f0be200427f92e3d034268fe38119730f87d1000d884651ea6d9187c8585c1cc3f0827b1f23f802" +
	"721501b0da521d8511da5d0e0768a82b9d6503d0209122689a2c8d0731245e0b85581c798203c80c4e94a1e9" +
	"e2290ba170121d81a6712c368824f1ea05058520d60b0ac4e9580d008010523d8cc5e83a4b906540ac529ca6" +
	"518624808281847d0e6268500a1981881a5e0ba058b83c11e3f03c4503442902079d6731566e1a03b8820a1d" +
	"20a16a2246785c0a63604082e01610c098e61f81300a85718a05c620881141f47982f190a98778d902235428" +
	"0460243b0410d019a1886883d142040740e30222b4630f60343ec400910b02cc5d8851ae0c4740e51743801f" +
	"04e11c18c3c8f70d62242a07c1a03b86386a0781c000089118160118ed030114610bb1183600d8bc10c0840a" +
	"0a31e83307b81e05602c7689f19010c1e0e708e1d8200570ca1cc158f606a2fc3e041008108200b61dc2c406" +
	"01f07a2fc5b09f10a00c6b07d10029c7f8b41543585e83613838c270040520e8108ef07401c0802b0d22a02e" +
	"0990c034c360d11e021c228f11e02d0640271b82a4578000521042306f0d23347489d046300208740e00741e" +
	"8e90ac2846900c1c82c0398d00220002789b0aa01c2708c00a094648900de24805824172014460e70f40a473" +
	"8e702a304508a81b42544c0f31b60902606511c020688b304e09c480be1662786085a1e81b8548de00039049" +
	"9010"

const (
	lzwRoundTripSeed = 12345
	lzwRoundTripSize = 12000
)

// TestLZWDecode proves LZWDecode decodes a TIFF LZW strip, round trips the
// early change settings, resets on a clear code, refuses malformed data with
// syntaxerror, and stops at the 32 MiB cap with limitcheck.
func TestLZWDecode(t *testing.T) {
	t.Parallel()
	checkLZWTiffStrip(t)
	checkLZWRoundTrip(t, 1)
	checkLZWRoundTrip(t, 0)
	checkLZWEarlyChangeDiffers(t)
	checkLZWMalformed(t)
	checkLZWCap(t)
	checkLZWClearMidStream(t)
}

// checkLZWTiffStrip decodes the Pillow TIFF strip and compares it with the
// same pixels generated by the Pillow script's generator.
func checkLZWTiffStrip(t *testing.T) {
	t.Helper()
	raw, err := hex.DecodeString(tiffLZWStrip)
	if err != nil {
		t.Fatal(err)
	}
	got, err := Decode(opLZW, NullVal(), raw)
	if err != nil {
		t.Fatal(err)
	}
	want := tiffStripPlain()
	if !bytes.Equal(got, want) {
		t.Fatalf("strip len %d, want %d", len(got), len(want))
	}
}

// tiffStripPlain builds the 32 by 32 pixel pattern the Pillow script wrote.
func tiffStripPlain() []byte {
	out := make([]byte, 32*32)
	state := int64(lzwRoundTripSeed)
	for i := range out {
		state = (1103515245*state + 12345) & 0x7fffffff
		out[i] = byte(state >> 16 & 0xff)
	}
	return out
}

func checkLZWRoundTrip(t *testing.T, early int) {
	t.Helper()
	plain := lzwPlainBytes()
	encoded := lzwEncode(t, plain, early)
	params := DictVal(map[string]Value{"EarlyChange": IntVal(int64(early))})
	got, err := Decode(opLZW, params, encoded)
	if err != nil {
		t.Fatalf("early %d: %v", early, err)
	}
	if !bytes.Equal(got, plain) {
		t.Fatalf("early %d: round trip len %d, want %d", early, len(got), len(plain))
	}
}

// checkLZWEarlyChangeDiffers proves the EarlyChange parameter reaches the
// decoder: the two encoders widen at different codes, so the streams differ.
func checkLZWEarlyChangeDiffers(t *testing.T) {
	t.Helper()
	plain := lzwPlainBytes()
	late := lzwEncode(t, plain, 0)
	early := lzwEncode(t, plain, 1)
	if bytes.Equal(late, early) {
		t.Fatal("EarlyChange 0 and 1 produced the same stream")
	}
	lateParams := DictVal(map[string]Value{"EarlyChange": IntVal(0)})
	got, err := Decode(opLZW, lateParams, late)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, plain) {
		t.Fatal("EarlyChange 0 stream did not decode")
	}
}

// lzwPlainBytes is deterministic pseudo-random data. The length passes 4095
// emitted codes, so the encoder issues a clear code mid-stream.
func lzwPlainBytes() []byte {
	out := make([]byte, lzwRoundTripSize)
	state := int64(987654321)
	for i := range out {
		state = (1103515245*state + 12345) & 0x7fffffff
		out[i] = byte(state >> 16 & 0xff)
	}
	return out
}

func checkLZWMalformed(t *testing.T) {
	t.Helper()
	cases := map[string][]byte{
		"truncated code": {0xff},
		"no eod":         lzwNoEOD(),
		"code past next": lzwBadCode(),
	}
	for name, raw := range cases {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			_, err := Decode(opLZW, NullVal(), raw)
			wantJob(t, err, opLZW, errSyntax)
		})
	}
}

// lzwNoEOD is a clear code, the literal A, and no end-of-data marker.
func lzwNoEOD() []byte {
	var out lzwBitWriter
	out.write(lzwClear, lzwStart)
	out.write('A', lzwStart)
	return out.bytes()
}

// lzwBadCode is a clear code, the literal A, and code 300 while the next
// table entry is 259.
func lzwBadCode() []byte {
	var out lzwBitWriter
	out.write(lzwClear, lzwStart)
	out.write('A', lzwStart)
	out.write(300, lzwStart)
	out.write(lzwEOD, lzwStart)
	return out.bytes()
}

// checkLZWClearMidStream decodes a leading literal and then a literal again
// after a clear, so the reset path runs.
func checkLZWClearMidStream(t *testing.T) {
	t.Helper()
	var out lzwBitWriter
	out.write(lzwClear, lzwStart)
	out.write('A', lzwStart)
	out.write('B', lzwStart)
	out.write(lzwClear, lzwStart)
	out.write('C', lzwStart)
	out.write(lzwEOD, lzwStart)
	got, err := Decode(opLZW, NullVal(), out.bytes())
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, []byte("ABC")) {
		t.Fatalf("clear reset %q", got)
	}
}

// checkLZWCap builds a table of long entries and then repeats the longest one
// until the 32 MiB cap stops the decode.
func checkLZWCap(t *testing.T) {
	t.Helper()
	raw := lzwGrowth()
	_, err := Decode(opLZW, NullVal(), raw)
	wantJob(t, err, opLZW, errLimit)
}

// lzwGrowth emits KwKwK codes that grow one byte per code to entry 4095, then
// repeats code 4095, whose expansion is 4096 bytes, past the cap.
func lzwGrowth() []byte {
	var out lzwBitWriter
	width := lzwStart
	next := lzwFirst
	out.write(lzwClear, width)
	out.write('A', width)
	for next <= lzwMaxCode {
		out.write(next, width)
		next++
		if width < lzwMaxWidth && next >= 1<<width-1 {
			width++
		}
	}
	for range 7000 {
		out.write(lzwMaxCode, width)
	}
	out.write(lzwEOD, width)
	return out.bytes()
}

// lzwEncode writes PDF LZW with the given EarlyChange setting. It is the
// mirror of lzwExpand, not a production encoder.
func lzwEncode(t *testing.T, plain []byte, early int) []byte {
	t.Helper()
	var out lzwBitWriter
	table := make(map[string]int, lzwMaxCode)
	reset := func() {
		clear(table)
		for i := range 256 {
			table[string([]byte{byte(i)})] = i
		}
	}
	reset()
	next := lzwFirst
	width := lzwStart
	out.write(lzwClear, width)
	add := func(key string) {
		if next > lzwMaxCode {
			out.write(lzwClear, width)
			reset()
			next = lzwFirst
			width = lzwStart
			return
		}
		table[key] = next
		next++
		if width < lzwMaxWidth && next >= (1<<width)-early+1 {
			width++
		}
	}
	prev := ""
	for _, cur := range plain {
		candidate := prev + string([]byte{cur})
		if _, ok := table[candidate]; ok {
			prev = candidate
			continue
		}
		out.write(table[prev], width)
		add(candidate)
		prev = string([]byte{cur})
	}
	if prev != "" {
		out.write(table[prev], width)
	}
	out.write(lzwEOD, width)
	return out.bytes()
}

// lzwBitWriter packs codes MSB first.
type lzwBitWriter struct {
	buf   []byte
	bits  byte
	count int
}

func (writer *lzwBitWriter) write(code, width int) {
	for i := width - 1; i >= 0; i-- {
		writer.bits <<= 1
		if code>>i&1 == 1 {
			writer.bits |= 1
		}
		writer.count++
		if writer.count == byteBits {
			writer.buf = append(writer.buf, writer.bits)
			writer.bits = 0
			writer.count = 0
		}
	}
}

func (writer *lzwBitWriter) bytes() []byte {
	if writer.count > 0 {
		writer.buf = append(writer.buf, writer.bits<<(8-writer.count))
	}
	return writer.buf
}
