// Code generated by gen.go; DO NOT EDIT.
//
// The standard 14 font list and the metrics lookup.

package font

var standard14Order = [14]string{
	"Courier",
	"Courier-Bold",
	"Courier-Oblique",
	"Courier-BoldOblique",
	"Helvetica",
	"Helvetica-Bold",
	"Helvetica-Oblique",
	"Helvetica-BoldOblique",
	"Times-Roman",
	"Times-Bold",
	"Times-Italic",
	"Times-BoldItalic",
	"Symbol",
	"ZapfDingbats",
}

var standard14Data = map[string]*Metrics{
	"Courier":               {name: "Courier", byName: courierByName, byCode: courierByCode},
	"Courier-Bold":          {name: "Courier-Bold", byName: courierBoldByName, byCode: courierBoldByCode},
	"Courier-Oblique":       {name: "Courier-Oblique", byName: courierObliqueByName, byCode: courierObliqueByCode},
	"Courier-BoldOblique":   {name: "Courier-BoldOblique", byName: courierBoldObliqueByName, byCode: courierBoldObliqueByCode},
	"Helvetica":             {name: "Helvetica", byName: helveticaByName, byCode: helveticaByCode},
	"Helvetica-Bold":        {name: "Helvetica-Bold", byName: helveticaBoldByName, byCode: helveticaBoldByCode},
	"Helvetica-Oblique":     {name: "Helvetica-Oblique", byName: helveticaObliqueByName, byCode: helveticaObliqueByCode},
	"Helvetica-BoldOblique": {name: "Helvetica-BoldOblique", byName: helveticaBoldObliqueByName, byCode: helveticaBoldObliqueByCode},
	"Times-Roman":           {name: "Times-Roman", byName: timesRomanByName, byCode: timesRomanByCode},
	"Times-Bold":            {name: "Times-Bold", byName: timesBoldByName, byCode: timesBoldByCode},
	"Times-Italic":          {name: "Times-Italic", byName: timesItalicByName, byCode: timesItalicByCode},
	"Times-BoldItalic":      {name: "Times-BoldItalic", byName: timesBoldItalicByName, byCode: timesBoldItalicByCode},
	"Symbol":                {name: "Symbol", byName: symbolByName, byCode: symbolByCode},
	"ZapfDingbats":          {name: "ZapfDingbats", byName: zapfDingbatsByName, byCode: zapfDingbatsByCode},
}
